// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BookLog struct {
	ID           pgtype.UUID
	Userid       pgtype.UUID
	Isbn13       string
	GoogleID     string
	Title        string
	ThumbnailUrl string
	Status       string
	Rating       pgtype.Float4
	Review       pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Shelf struct {
	ID          pgtype.UUID
	Userid      pgtype.UUID
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ShelfBook struct {
	ShelfID      pgtype.UUID
	Isbn13       string
	GoogleID     string
	Title        string
	ThumbnailUrl pgtype.Text
	AddedAt      pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	PasswordHash pgtype.Text
	GoogleID     pgtype.Text
	Name         pgtype.Text
	AvatarUrl    pgtype.Text
}
