// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserOrUpdate = `-- name: CreateUserOrUpdate :one
INSERT INTO users (email, google_id, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email)
DO UPDATE SET
    google_id = EXCLUDED.google_id,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, email, created_at, updated_at, google_id, name, avatar_url
`

type CreateUserOrUpdateParams struct {
	Email     string
	GoogleID  pgtype.Text
	Name      pgtype.Text
	AvatarUrl pgtype.Text
}

func (q *Queries) CreateUserOrUpdate(ctx context.Context, arg CreateUserOrUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserOrUpdate,
		arg.Email,
		arg.GoogleID,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}
